MAIN_METRICS = {
    'A plazo (incluye inversiones y excluye CEDROS) (en millones de pesos)': 'Term investments (Mio $)',
    'BADLAR en pesos de bancos privados (en % e.a.)': 'BADLAR (% e.a.)',
    'BADLAR en pesos de bancos privados (en % n.a.)': 'BADLAR (% n.a.)',
    'Base monetaria - Total (en millones de pesos)': 'Monetary base (Mio $)',
    'Billetes y monedas en poder del publico (en millones de pesos)': 'Public money (Mio $)',
    'CER (Base 2.2.2002=1)': 'CER (Base 2.2.2002=1)',
    'Circulacion monetaria (en millones de pesos)': 'Currency circulation (Mio $)',
    'Depositos de los bancos en cta. cte. en pesos en el BCRA (en millones de pesos)': 'Bank deposits in BCRA (Mio $)',
    'Depositos en efectivo en las entidades financieras - Total (en millones de pesos)': 'Cash deposits - financial entities (Mio $)',
    'Efectivo en entidades financieras (en millones de pesos)': 'Cash in financial entities (Mio $)',
    'En Caja de ahorros (en millones de pesos)': 'Savings bank (Mio $)',
    'En cuentas corrientes (neto de utilizacion FUCO) (en millones de pesos)': 'Current account (Mio $)',
    'Indice para Contratos de Locacion (ICL-Ley 27.551, con dos decimales, base 30.6.20=1)': 'ICL Index',
    'Inflacion esperada - REM proximos 12 meses - MEDIANA (variacion en % i.a)': 'Expected inflation rate next 12 months', 
    'Inflacion interanual (variacion en % i.a.)': 'Inflation Rate (YoY)',
    'Inflacion mensual (variacion en %)': 'Monthly Inflation Rate',
    'M2 privado, promedio movil de 30 dias, variacion interanual (en %)': 'M2 (YoY %)',
    'Pases pasivos para el BCRA - Saldos (en millones de pesos)': 'Reverse swaps (Mio $)',
    'Prestamos de las entidades financieras al sector privado (en millones de pesos)': 'Financial entities loans (Mio $)',
    'Reservas Internacionales del BCRA (en millones de dolares - cifras provisorias sujetas a cambio de valuacion)': 'BCRA Reserves (Mio USD)',
    'TM20 en pesos de bancos privados (en % n.a.)': 'TM20 (% n.a.)',
    'Tasa de Politica Monetaria (en % e.a.)': 'Monetary policy rate (% e.a)',
    'Tasa de Politica Monetaria (en % n.a.)': 'Monetary policy rate (% n.a)',
    'Tasa de interes de prestamos personales': 'Personal loans rate',
    'Tasa de interes de prestamos por adelantos en cuenta corriente': 'Interest rate loans in cta cte',
    'Tasas de interes de las operaciones de pase activas para el BCRA, a 1 dia de plazo (en % n.a.)': 'Interest rate active swaps (% n.a.)',
    'Tasas de interes de las operaciones de pase pasivas para el BCRA, a 1 dia de plazo (en % e.a.)': 'Interest rate passive swaps (% e.a.)',
    'Tasas de interes de las operaciones de pase pasivas para el BCRA, a 1 dia de plazo (en % n.a.)': 'Interest rate passive swaps (% n.a.)',
    'Tasas de interes por depositos a 30 dias de plazo en entidades financieras (en % n.a.)': 'Interest rate 30 days financial entities (% n.a.)',
    'Tasas de interes por prestamos entre entidades financiera privadas (BAIBAR) (en % n.a.)': 'BAIBAR (% n.a.)',
    'Tipo de Cambio Mayorista ($ por USD) Comunicacion A 3500 - Referencia': 'Wholesale Exchange Rate',
    'Tipo de Cambio Minorista ($ por USD) Comunicacion B 9791 - Promedio vendedor': 'Exchange Rate',
    'Unidad de Valor Adquisitivo (UVA) (en pesos -con dos decimales-, base 31.3.2016=14.05)': 'UVA (base 31.3.2016=14.05)',
    'Unidad de Vivienda (UVI) (en pesos -con dos decimales-, base 31.3.2016=14.05)': 'UVI (base 31.3.2016=14.05)'
}